### ISSUE TITLE
Help with deploying in vercel

### ISSUE THREAD

**Issue by agustinbrand** [copilot-is/copilot.is#1]
![image](https://github.com/user-attachments/assets/a65e4538-6833-4589-b58e-3ca71960a02b)
Hey, how is it going? 

I got this errors when trying to auth in any way, i already added the github and google variables

Can you help me?

**Comment by agustinbrand** [comment]
Fixed, forgot to create db

**Comment by chats-is** [comment]
Google login
Go to the [Google console](https://console.developers.google.com/apis/credentials) **CREATE CREDENTIALS >> OAuth client ID**

Create db
Creating a Vercel Postgres Instance
https://vercel.com/docs/storage/vercel-postgres/quickstart
Connect Project

Vercel Build & Development Settings
Install Command `pnpm install && pnpm db:push`

**Comment by agustinbrand** [comment]
Is there a way to bring back credentials login? I have to try to check in another API if the user is active or not, and let them in based on that

**Comment by chats-is** [comment]
I don't quite understand
